### ISSUE TITLE
Useless switch statement

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/dooboo-ui#52]
https://github.com/dooboolab/dooboo-ui/blob/d9721babfd7a6d8a20172bdef3e775d617c2cb8c/docs/src/components/ButtonGroup/index.tsx#L32-L40

https://github.com/dooboolab/dooboo-ui/blob/d9721babfd7a6d8a20172bdef3e775d617c2cb8c/stories/dooboo-ui/ButtonGroupStories/index.tsx#L33-L41

I think switch statement is uselsss here. Am I missing something?

**Comment by hyochan** [comment]
@yujong-lee Nope you've exactly caught the redundancy. Looks like we can remove that. Moreover, the examples for [ButtonGroup] are currently in naive status. Mostly because they are minimally delivered from our `legacy` project.

### What I am looking for
When providing some advanced samples for each component, we might be able to look into some limitations and we can improve our component more flexibly.

**Comment by yujong-lee** [comment]
Resolved by #56. [This] is moved to new issue.
